#!/bin/bash

FAILED_COUNT=0

while read oldrev newrev refname
do
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $refname)
    WORK_DIR="clientbranches/$GIT_PUSH_OPTION_0"

    mkdir -p $WORK_DIR

    git --work-tree=$WORK_DIR checkout -f
    git --work-tree=$WORK_DIR checkout master
    git --work-tree=$WORK_DIR merge $BRANCH


    if [ $? -eq 0 ]
    then
        echo "merged $BRANCH"
    else
        ((FAILED_COUNT++))
        git --work-tree=$WORK_DIR merge --abort
        echo "ERROR: can't merge $BRANCH to master."
    fi
done

if [ $FAILED_COUNT -eq 0 ]
then
    echo "it was nice syncing with you"
else
    echo "Please merge the failed branches localy"
    exit 111
fi



