#!/bin/bash

if [ ! -z "$OCTO_CHAINSAW_DIR" ]
then
    cd $OCTO_CHAINSAW_DIR
fi

if [ -f ".octo_chainsaw_lock" ]
then
    echo ".octo_chainsaw_lock exists. Stopping."
    exit 1
fi

git fetch || exit $?

git merge origin/master --no-edit 
if [ "$?" -ne "0" ] 
then
    git merge --abort
    exit 222
fi



