#!/bin/bash

while getopts 'lha:' OPTION; do
    case "$OPTION" in
        l)
            IGNORE_LOCK=1
            ;;
        ?) 
            echo "unknown option"
            exit 42
            ;;
    esac
done

if [ ! -z "$OCTO_CHAINSAW_DIR" ]
then
    cd $OCTO_CHAINSAW_DIR
fi

if [ ! -z "$OCTO_CHAINSAW_ORIGIN" ]
then
    echo "using git origin '$OCTO_CHAINSAW_ORIGIN' to get changes"
fi

if [ -f ".octo_chainsaw_lock" ]
then
    if [ -n "$IGNORE_LOCK" ]
    then
        echo "ignoring lock"
    else
        echo ".octo_chainsaw_lock exists. Stopping."
        CODE_FROM_LOCK=$(cat .octo_chainsaw_lock)
        if [ -z "$CODE_FROM_LOCK" ]
        then
            CODE_FROM_LOCK=123
        fi
        exit "$CODE_FROM_LOCK"
    fi
fi

echo "fetching $OCTO_CHAINSAW_ORIGIN"
git fetch $OCTO_CHAINSAW_ORIGIN || exit $?

echo "merging master"
git merge origin/master --no-edit 
if [ "$?" -ne "0" ] 
then
    git merge --abort
    echo 222 > .octo_chainsaw_lock
    exit 222
fi



